### PR TITLE
Implement idea in issue 52

### PR DESCRIPTION
**Pull request by clemens-fricke**
Relates to #52

### CODE REVIEW

**Comment by jzwar** [comment]
Now that the ground work is there we should think about how to store the inverse matrix to make it a little more efficient and also we should implement it into the ffd framework

**Comment by j042** [comment]
let's first merge #54 before this?

**Comment by j042** [comment]
can you move all querying functions to `splinepy`?

**Comment by j042** [comment]
I guess this one is inactive. feel free to reopen if it is!

**Pull request closed without merging**
