### PR TITLE
Ft add update + v0.0.25

### PR DESCRIPTION
**Pull request by j042**
Adds `DataHolder.update()` and bump version

As part of v0.0.25 this PR also includes:
- helper tests
- io export signature `export(fname, mesh)` instead of other way around
- workflow updates

### CODE REVIEW

**Review by clemens-fricke — APPROVED** [review]
Looks good, Thank You. Only a test would be nice to have.

**Comment by j042** [comment]
> > Looks good, Thank You. Only a test would be nice to have.
> 
> good idea!

working on some test for helpers. I will create a new PR for it

**Comment by clemens-fricke** [comment]
Thank you. Merge it at will.

**Comment by j042** [comment]
need to update workflow - `macos-latest` is now arm

**Review by danielwolff1 — APPROVED** [review]
I took a glance at the changes and it's looking good from my side, including the test!

**Pull request merged**
