### PR TITLE
Adding vertex and face groups to meshes

### PR DESCRIPTION
**Pull request by CodeFloh**
## Related Issues ##

#18 - Storage and maintenance of volume, face and vertex groups

## Description ##

This PR adds vertex groups to Vertices and face groups to Faces. The conversion of vertex to face groups and the other way around is also possible. Furthermore, vertex and face groups can be extracted into independent instances of Vertices and Faces, mostly for display purposes.

The functionality will be demonstrated in the HyperMesh import PR.

## Remarks ##

- The edge and volume groups are missing. If the current draft is approved, they will be added in the same manner, along with `get_element_groups()` and `get_subelement_groups()` getters.
- The function `get_faces()` is heavily used in the current implementation. Does it make sense to check for an existing `faces` array instead? Is that always up-to-date?

### CODE REVIEW

**Comment by j042** [comment]
Just to quickly answer the remarks:
`geom.get_<whatever>` is there to make sure whatever you want is freshly computed. Those values are saved in `geom.<whatever>` and the value of them won't change unless you change it directly or you have in-place changes then call `get_<whatever>`.

> * The edge and volume groups are missing. If the current draft is approved, they will be added in the same manner, along with `get_element_groups()` and `get_subelement_groups()` getters.
- element groups on the other hand is not so easy to incorporate in-place changes. meaning we need to prevent it. (BC) as well. I do have an idea if you wanna go this way
> * The function `get_faces()` is heavily used in the current implementation. Does it make sense to check for an existing `faces` array instead? Is that always up-to-date?

- No, then it makes more sense to make a getter for faces. I had it like that in `gustav` and I ran into some situation where I got the wrong values then I expected. In this case, if you want to recompute, you either have to remove the flag or saved value directly. For this one I wanted to make sure saved one and recomputing is separately available. `f_or_v.faces` <- will be what you are looking for, I guess.

General outlook on this one is that we add a flag `no_inplace` to return saved values if available. But it kinda breaks the idea that I've just mentioned, but I haven't decided whether that'd be a good super power or super confusing

**Comment by CodeFloh** [comment]
Thanks for your reply. I only wanna comment on thing:

> > * The edge and volume groups are missing. If the current draft is approved, they will be added in the same manner, along with `get_element_groups()` and `get_subelement_groups()` getters.
> 
>     * element groups on the other hand is not so easy to incorporate in-place changes. meaning we need to prevent it. (BC) as well. I do have an idea if you wanna go this way

I actually haven't thought about this. Is this something that we can solve later on? Otherwise I could imagine adding some check() routines that can be used before mesh export to make sure all the referenced elements or vertices still exist.

BTW, I will rebase this on top of my extrusion PR so I can combine the features.

**Comment by CodeFloh** [comment]
This PR is getting a bit crazy. We should probably talk about Vedo and plotting routines. Also about the best place for the group extraction routines and their architecture.

**Comment by j042** [comment]
What we talked about yesterday would be:
```python
class _VertexGroups:
    """I help Vertices"""
    
    def __init__(self, vertices_obj):
        self.v = vertices_obj
    ...
    def extract(group_name):
        ...
        return type(self.v)(<extracted-vertices>)

class Vertices:
    def __init__(...):
        ...
        self._vgroups = _VertexGroups(self)
        ...
    ...
    @property
    def vgroups(self):
        return self._vgroups
```
The use case may look something like:
```python
v = Vertices(<nice-vertices>)
v.vgroups["g"] = <g-ids>
v.vgroups["u"] = <u-ids>
...
s_group_vs = v.vgroups.extract("s")
```
I plan to update `__init__` for Edges, Faces, Volumes, so that they'd use super's init. So maybe that way we can avoid some redundant implementations.   
Is there any other use of this grouping class? If not, I'd suggest that we implement this in its "helpee" class' file directly, instead of putting it in `gustaf/utils`

**Comment by CodeFloh** [comment]
This class already exists: https://github.com/tataratat/gustaf/blob/844eac386c5b05799fc0199bf01104001fab5ca8/gustaf/utils/groups.py#L83

But it doesn't work like that. `type(self.v)` (or in my code `self.mesh`) could be either Vertices, Edges, Faces or Volumes. But the result of the extraction routine must always be Vertices. That's why I couldn't put the extraction routines with the group classes. The only alternative I see that avoids cyclic dependencies would be a third file that can import both the mesh types and group types. But this would create ugly (non-object-oriented) code like:

`extracted_vertex_mesh = extract_vertex_group(vertices, "group_name")`

**Comment by CodeFloh** [comment]
> I plan to update `__init__` for Edges, Faces, Volumes, so that they'd use super's init. So maybe that way we can avoid some redundant implementations.

This would be good. I was thinking about doing that anyway, but I decided to use a separate routine that uses that principle, so I wouldn't have to mess too much with the existing code:

https://github.com/tataratat/gustaf/blob/844eac386c5b05799fc0199bf01104001fab5ca8/gustaf/volumes.py#L55

**Comment by j042** [comment]
> But it doesn't work like that. `type(self.v)` (or in my code `self.mesh`)

then `type(self.v.tovertices())`? and minor modifications at `tovertices()`, where it also takes current group info

**Comment by CodeFloh** [comment]
> then `type(self.v.tovertices())`? and minor modifications at `tovertices()`, where it also takes current group info

That's a bit hacky isn't it? With this type of code you run the risk of needlessly executing expensive functions just to find out their return types.

**Comment by j042** [comment]
true, what about `return self.v.tovertices().extract(*args)`?

**Comment by CodeFloh** [comment]
> true, what about `return self.v.tovertices().extract(*args)`?

But then you would have `mesh.vertex_groups.extract_vertex_group(group_name)` as a shortcut for `mesh.extract_vertex_group(group_name)` which is shorter?

I kind of think external non-class-member functions as I suggested earlier are perhaps the cleanest solution.

**Comment by j042** [comment]
I think it is unnecessary to directly populate "mesh" types with these operations. If we are going to have a helper class, why don't we unload all the related operations to that? That'd would mean removing `mesh.extract_vertex_group(group_name)` and only keeping `mesh.vertex_groups.extract(group_name)`.

> ... external non-class-member functions ...

What do you mean by that?

**Comment by CodeFloh** [comment]
> That'd would mean removing `mesh.extract_vertex_group(group_name)` and only keeping `mesh.vertex_groups.extract(group_name)`.

It doesn't work because of cyclic dependencies.

The mesh types (e.g. `Volumes`) have to know and import the group types (e.g. `VolumeGroupCollection`) so that they can initialize the objects. Then the group types cannot import the mesh types. But they would need to know the mesh types for the extraction operations, unless something 'hacky' happens. So the only other option seems to be global functions in a third file that can import both the mesh types and the group types.

**Comment by j042** [comment]
why would that be a cyclic dependency if you use tovertices(), toedges(), ... to generate extracted elements?

**Comment by CodeFloh** [comment]
> why would that be a cyclic dependency if you use tovertices(), toedges(), ... to generate extracted elements?

Do you mean

```
return type(mesh.tofaces())(...)
```

or do you mean

```
return mesh.tofaces(unique=False).get_element_groups().extract_element_group(group_name)
```

?

The former would lead to an unnecessary execution of the Faces() constructor, while the latter would require exporting groups in `to*()` routines, but should otherwise not hurt the performance.

However, I think an external function like the following might actually be the cleanest way in the end:

```
extract_face_group(faces, "left").shrink().show()
```

**Comment by j042** [comment]
Ah ok, now I understand what you meant by external function.
Putting together what we've been talking about, what about something like this?

```python
class Groups:
    """iambase"""
    ...
    ...
    @classmethod
    def tovertices(cls, mesh, vertices_group_name):
        """we can use this as external function"""
        vs = mesh.tovertices(unique=False)
        # check if `vertices_group_name` exists
        id_to_extract = mesh.vgroups.get(vertices_group_name, None)
        if id_to_extract is None:
            return None
        
         vs.vertices = vs.vertices[id_to_extract]

         return vs

class VertexGroups(Groups):
    """I help Vertices"""
    
    def __init__(self, vertices_obj):
        self.v = vertices_obj

    ...
    ...
    def extract(self, group_name):
        """easy access"""
        return Groups.tovertices(self.v, group_name)
    ...
    ...

class Vertices:
    def __init__(...):
        ...
        self._vgroups = _VertexGroups(self)
        ...
    ...
    @property
    def vgroups(self):
        return self._vgroups
```

**Comment by j042** [comment]
Closing this for now, let's revisit this later when gustaf is ready for it

**Comment by j042** [comment]
just a thought: would you like to put some creation routines from this PR to `gustaf/examples/experimental`?  I guess without grouping functionalities for now

**Pull request closed without merging**
